### PR TITLE
Create index.js

### LINKED ISSUE #2: jtrj
hmjhtrj

### PR DESCRIPTION
**Pull request by TtgNoob**
# 📑 DESCRIPTION

Issue Number : #2 
### ❓ What has been changed : 

Fixes #2

### CODE REVIEW

**Comment by TtgNoob** [comment]
!check

**Comment by TtgNoob** [comment]
!check

**Comment by HardikGuptaDev** [comment]
!check

**Comment by HardikGuptaDev** [comment]
!check

**Comment by TtgNoob** [comment]
!check

**Comment by TtgNoob** [comment]
!check

**Comment by TtgNoob** [comment]
!check

**Comment by TtgNoob** [comment]
!assign

**Comment by TtgNoob** [comment]
!check

**Comment by TtgNoob** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good

**Pull request merged**
